/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.17
 * Generated at: 2019-04-10 08:55:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Team3_005fMedia.Team3_005fMedia.WebContent.Media;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Youtube_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Media_YouTube</title>\n");
      out.write("<style type=\"text/css\">\n");
      out.write("    .header {\n");
      out.write("\tbackground-color: #0097e6;\n");
      out.write("} \n");
      out.write("    .col-1 {\n");
      out.write("      width: 8.33%;\n");
      out.write("    }\n");
      out.write("    .col-2 {\n");
      out.write("      width: 16.66%;\n");
      out.write("    }\n");
      out.write("    .col-3 {\n");
      out.write("      width: 25%;\n");
      out.write("    }\n");
      out.write("    .col-4 {\n");
      out.write("      width: 33.33%;\n");
      out.write("    }\n");
      out.write("    .col-5 {\n");
      out.write("      width: 41.66%;\n");
      out.write("    }\n");
      out.write("    .col-6 {\n");
      out.write("      width: 50%;\n");
      out.write("    }\n");
      out.write("    .col-7 {\n");
      out.write("      width: 58.33%;\n");
      out.write("    }\n");
      out.write("    .col-8 {\n");
      out.write("      width: 66.66%;\n");
      out.write("    }\n");
      out.write("    .col-9 {\n");
      out.write("      width: 75%;\n");
      out.write("    }\n");
      out.write(".col-10 {\n");
      out.write("    width: 83.33%;\n");
      out.write("  }\n");
      out.write("  .col-11 {\n");
      out.write("    width: 91.66%;\n");
      out.write("  }\n");
      out.write("  .col-12 {\n");
      out.write("    width: 100%;\n");
      out.write("  }\n");
      out.write(".container {\n");
      out.write("    margin: 0 auto;\n");
      out.write("    height: 550px;\n");
      out.write("    background-color: white;\n");
      out.write("  }\n");
      out.write("  .article-a {\n");
      out.write("    float: left;\n");
      out.write("    width: 50%;\n");
      out.write("    height: 40%;\n");
      out.write("    background-color: white;\n");
      out.write("    padding: 10px;\n");
      out.write("    color: #201F20;\n");
      out.write("    text-align: center;\n");
      out.write("    margin-bottom: 20px;\n");
      out.write("    margin-top: 10px; \n");
      out.write("   \n");
      out.write("  }\n");
      out.write("  .article-b {\n");
      out.write("    float: left;\n");
      out.write("    width: 50%;\n");
      out.write("    height: 40%;\n");
      out.write("    background-color: white;\n");
      out.write("    padding: 10px;\n");
      out.write("    color: #201F20;\n");
      out.write("    text-align: center;\n");
      out.write("    margin-bottom: 20px;\n");
      out.write("    margin-top: 10px;\n");
      out.write("  }\n");
      out.write("  .footer {\n");
      out.write("    clear: both;\n");
      out.write("    padding: 10px;\n");
      out.write("    background-color: white;\n");
      out.write("    color: black;\n");
      out.write("  }\n");
      out.write("  .footer h3 {\n");
      out.write("    text-align: center;\n");
      out.write("  }\n");
      out.write("  \n");
      out.write("\n");
      out.write("</style>\n");
      out.write("<link rel=\"stylesheet\" href=\"index.css\">\n");
      out.write("<!-- Latest compiled and minified CSS -->\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\">\n");
      out.write("<!-- jQuery library -->\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\n");
      out.write("<!-- Popper JS -->\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\"></script>\n");
      out.write("<!-- Latest compiled JavaScript -->\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/Team3_Media/Team3_Media/WebContent/commonmodule/Top.jsp", out, false);
      out.write("\n");
      out.write("<div class = \"col-12\" > \n");
      out.write("<h1>HTML &nbsp; <img src=\"../images/youtube.png\" style=\"width:50px; height:50px; margin-bottom:10px\" ></img>&nbsp;<b>YouTube</b></h1>\n");
      out.write("<hr>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class = \"article-a\">\n");
      out.write("<p>iFrame 재생</p>\n");
      out.write("<iframe width=\"440\" height=\"245\" src=\"https://www.youtube.com/embed/9sFUryyoJCw\">\n");
      out.write("</iframe>\n");
      out.write("<br>\n");
      out.write("<br>\n");
      out.write("<br>\n");
      out.write("\n");
      out.write("\n");
      out.write("<p>Auto play 재생(<span style=\"color:red\">현재 Chrome에서 막아놓음</span>)</p>\n");
      out.write("<iframe width=\"440\" height=\"245\" src=\"https://www.youtube.com/embed/9sFUryyoJCw?autoplay=1\" allow=\"autoplay; encrypted-media\";\">\n");
      out.write("</iframe> \n");
      out.write("<br>\n");
      out.write("<br>\n");
      out.write("<br>\n");
      out.write("<p>Object 재생</p>\n");
      out.write("<object width=\"440\" height=\"245\"\n");
      out.write("data=\"https://www.youtube.com/embed/9sFUryyoJCw\">\n");
      out.write("</object>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class = \"article-b\">\n");
      out.write("<p>Loop</p>\n");
      out.write("<iframe width=\"440\" height=\"245\" src=\"https://www.youtube.com/embed/9sFUryyoJCw?playlist=9sFUryyoJCw&loop=1\">\n");
      out.write("</iframe>\n");
      out.write("<br>\n");
      out.write("<br>\n");
      out.write("<br>\n");
      out.write("\n");
      out.write("\n");
      out.write("<p>Control bar 제거</p>\n");
      out.write("<iframe width=\"440\" height=\"245\" src=\"https://www.youtube.com/embed/9sFUryyoJCw?controls=0\">\n");
      out.write("</iframe>\n");
      out.write("<br>\n");
      out.write("<br>\n");
      out.write("<br>\n");
      out.write("<p>Embed 재생</p>\n");
      out.write("<embed width=\"440\" height=\"245\"\n");
      out.write("src=\"https://www.youtube.com/embed/9sFUryyoJCw\">\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
